### ISSUE TITLE
SNOW-1493073: SQL text not shown if it fails to execute

### ISSUE THREAD

**Issue by padhia** [snowflakedb/snowflake-cli#1243] opened 2024-06-20 18:40 UTC
### SnowCLI version

2.4.0

### Python version

3.11.9

### Platform

macOS-14.5-arm64-arm-64bit

### What happened

The SQL text is not shown if it fails to execute. `snowsql` on the other hand prints (with `echo=true` option) SQL regardless of the outcome of the SQL execution. 

I'd think having SQL displayed is even more useful when there is an error rather than only when there is no error.

### Console output

```Shell
> snow sql -q "sel 'Hello World!'"                                                                                                                                
An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

001003 (42000): 01b52411-080a-38b5-0000-4329785f1e9e: SQL compilation error:
syntax error line 1 at position 0 unexpected 'sel'.
```

**Comment by sfc-gh-pczajka** [comment] 2024-06-24 11:14
I'm closing this issue as it's a duplicate of https://github.com/snowflakedb/snowflake-cli/issues/1145

**Closed** 2024-06-24 11:14 UTC
